### ISSUE TITLE
Add Configuration to SPI, and add DMA/Interrupt support for Transmit and Receive

### ISSUE THREAD

**Issue by stephenhensley** [electro-smith/libDaisy#161]
something to fix up similar to other peripherals (like i2c, etc.)

**Comment by andrewikenberry** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Flexible SPI interface (all configurations for Rx and Tx)](https://trello.com/c/tSEWp74r/16-flexible-spi-interface-all-configurations-for-rx-and-tx)

**Comment by stephenhensley** [comment]
Configuration is handled -- We'll open a whole new set of issues for the new additions (DMA, etc.) post v0.1
