### ISSUE TITLE
Replace Daisy_Seed_Rev2_Pinout.csv with the shipping seed pinout

### ISSUE THREAD

**Issue by ggsubs** [electro-smith/libDaisy#196]
The current pinout at https://github.com/electro-smith/libDaisy/blob/master/doc/Daisy_Seed_Rev2_Pinout.csv is not the latest shipping seed pinout. It can lead to confusion.

**Comment by stephenhensley** [comment]
Thanks for pointing this out. Resolving now.

We'll be publishing a hardware repo a little later that contains schematics, etc. as well.
