### ISSUE TITLE
MidiHandler buffers MIDI messages from UART

### ISSUE THREAD

**Issue by trisiak** [electro-smith/libDaisy#218]
I was playing with the [Midi example](https://github.com/electro-smith/DaisyExamples/tree/master/pod/Midi) and hit a frustrating bug. After connecting a MIDI controller over UART (the MIDI jack on the POD), the messages were not available from the `MidiHandler` immediately but needed to get "pushed", i.e. a NoteOn was only getting processed after its NoteOff was sent by the controller.

I think that the delay is caused by the size of DMA buffer set at https://github.com/electro-smith/libDaisy/blob/72827e1b9f3f75031f5320ec5c8ee8a78ba95c78/src/hid_midi.cpp#L34 The only callback that `hid_midi.cpp` sets is triggered when the transfer is complete, and the regular MIDI messages have 2 and 3 bytes only. I think that this means a single message sits in the buffer until full 6 bytes are received.

Adjusting the DMA buffer size from 6 to 1 solves my problem and the MIDI messages are now available to my program immediately. I suspect that it's introducing a risk of losing incoming data and the correct approach would be to rely on the `HAL_UART_RxHalfCpltCallback` callback while setting the data transfer to 2 or 3 bytes but I'm not knowledgeable enough.

**Comment by stephenhensley** [comment]
Good catch, you're absolutely correct. The UART buffer should be at most 3, here. But keeping 2-byte messages in mind, it should probably just be one. I'm sure there's a way to deal with this a bit more efficiently. I can get this fixed here this week.
