### ISSUE TITLE
Buttons 1 and 2 reversed on Daisy Pod  (seed rev4 + pod rev3) ?

### ISSUE THREAD

**Issue by MrBlueXav** [electro-smith/libDaisy#245]
still searching...

**Comment by MrBlueXav** [comment]
I fixed the problem in daisy_pod.cpp with :

#define SW_1_PIN 27
#define SW_2_PIN 28

**Comment by HartmutG** [comment]
Indeed, I can confirm, swapping the pins is the solution.
I also wanted to report the issue and the solution, but saw that there is already a report about it.
So no new issue.

**Comment by stephenhensley** [comment]
Good catch! I swear I thought we've fixed this like 5 times already 😆 

Should be good now (and any examples that had them mapped backwards to be compensate in Daisy examples are also being fixed).
