### ISSUE TITLE
FatFs stops working when audio is running

### ISSUE THREAD

**Issue by hexcode0x** [electro-smith/libDaisy#252]
Posted minimal example code at: https://forum.electro-smith.com/t/fatfs-errors-on-sd-card-when-audio-is-enabled/572

When anything but a small number of reads is done in the main loop and audio is enabled, FatFs errors out and stops working.

Without audio interrupts, it is 100% reliable.

I suspect that even with a small number of reads in the main loop this could still happen, if the timing happens to hit an audio interrupt.  The example code uses the bare minimum audio callback possible, so this isn't an issue with the audio interrupt taking up too much time.

**Comment by stephenhensley** [comment]
This should be resolved as of #311
