### ISSUE TITLE
double stm32h7xx_hal_conf.h

### ISSUE THREAD

**Issue by grrrr** [electro-smith/libDaisy#275]
Hi, the stm32h7xx_hal_conf.h config file is present twice in the libdaisy folder structure
1) at /src/sys
2) at /core
Obviously the former is chosen by the libdaisy build, while the latter is chosen using the $(LIBDAISY_DIR)/core/Makefile for user projects.

**Comment by stephenhensley** [comment]
oh good catch, probably happened when we reorganized all the folder (I just found a bunch of duplicates of these in the DaisyExamples projects as well (already cleaned out most, if not all of those, though).
