### ISSUE TITLE
Redundant double precision multiply

### ISSUE THREAD

**Issue by GregBurns** [electro-smith/libDaisy#281]
I habitually compile with  -Wdouble-promotion to catch inadvertant double precision operations where float is just fine. I recently started to see the warnings below. Since the value returned is a float I can't see any benefit from a double precision multiply. The obvious fix is to define S322F_SCALE as a float constant.

../Daisy/libdaisy/src/daisy_core.h: In function 'float s322f(int32_t)':
../Daisy/libdaisy/src/daisy_core.h:96:21: warning: implicit conversion from 'float' to 'double' to match other operand of binary expression [-Wdouble-promotion]
   96 |     return (float)x * S322F_SCALE;

**Comment by stephenhensley** [comment]
oh snap -- totally just a missing `f` in the definition of `S322F_SCALE`:
`#define S322F_SCALE 4.6566129e-10 `

Good catch -- I hate redundant double precision, and usually pick apart my programs' disassembly when they're close to finished looking for signs of this.

I'll patch this shortly!
