### ISSUE TITLE
ADC averaging not tracking audio callback rate changes

### ISSUE THREAD

**Issue by GregBurns** [electro-smith/libDaisy#297]
The ADC controller initialization uses the default audio frequency and blocksize to compute the slew parameters. If these are subsequently changed the slew rate is no longer valid and can be off by a lot. For example, the default audio callback frequency is 1KHz but with an audio block size of 256 at 32KHz sample rate, the callback frequency is only 125Hz. The controller Init() api is private so calling that after changing the sample rate and block size is not an option.

**Comment by stephenhensley** [comment]
I can push a fix for this in the next few days.

I'll add a `SetCallbackRate` function to the `AnalogControl` class, and have the `SetBlockSize` and `SetSampleRate` functions recompute, and set this from the DaisySeed API.

**Comment by stephenhensley** [comment]
So I just opened #303 which adds a SetCoeff function which I think is ultimately more useful than a 'samplerate'  or 'slewtime' control so that the filter is directly controllable.
