### ISSUE TITLE
Add conversion s28f() (int8_t to float)

### ISSUE THREAD

**Issue by makingsoundmachines** [electro-smith/libDaisy#305]
Feature suggestion: it would be nice to have conversion int8_t to float to the daisy core.

https://github.com/electro-smith/libDaisy/blob/master/src/daisy_core.h

I used this today to use some 8bit SID noise code with DaisySP, that generates int8_t as its output.

```
#define S82F_SCALE 0.00390625f     /**< 1 / (2**8) */
#define F2S8_SCALE 255.0f          /**< (2 ** 8) - 1 */


FORCE_INLINE float s82f(int8_t x)
{
    return (float)x * S82F_SCALE;
}

FORCE_INLINE int8_t f2s8(float x)
{
    x = x <= FBIPMIN ? FBIPMIN : x;
    x = x >= FBIPMAX ? FBIPMAX : x;
    return (int32_t)(x * F2S8_SCALE);
}
```

**Comment by beserge** [comment]
Two small thoughts:
1. I think  `S82F_SCALE` should be `1/((2**8) - 1) = 1/255`, that way we'll get all the way to 1.f at 255.
2. The conversion to float should probably be bipolar. i.e. 0 will map to -1.f and 255 will map to 1.f. This would look something like
```
#define S82F_SCALE 0.00784313f     /**< 2 / 255 */
FORCE_INLINE float s82f(int8_t x)
{
    return (float)x * S82F_SCALE - 1.f;
}
```
